<?php
return [
    "addUserModules" => [
        'MASA', 'VIRGINIA', 'IBOAPP', 'ABEPLAYERTV', "BOBPLAYER",
        "MACPLAYER", "KTNPLAYER", "ALLPLAYER", "HUSHPLAY", "FAMILYPLAYER", "KING4KPLAYER", "IBOSSPLAYER", "IBOXXPLAYER", "BOBPROTV", "IBOPROTV","IBOSTB","IBOSOL", "DUPLEX", "FLIXNET"
        
    ],
    "editUserModules" => [
        'MASA', 'VIRGINIA', 'IBOAPP', 'ABEPLAYERTV', "BOBPLAYER",
        "MACPLAYER", "KTNPLAYER", "ALLPLAYER", "HUSHPLAY", "FAMILYPLAYER", "KING4KPLAYER", "IBOSSPLAYER", "IBOXXPLAYER", "BOBPROTV", "IBOPROTV","IBOSTB","IBOSOL", "DUPLEX", "FLIXNET"
    ],
    "userDetailModules" => [
        'MASA', 'VIRGINIA', 'IBOAPP', 'ABEPLAYERTV', "BOBPLAYER",
        "MACPLAYER", "KTNPLAYER", "ALLPLAYER", "HUSHPLAY", "FAMILYPLAYER", "KING4KPLAYER", "IBOSSPLAYER", "IBOXXPLAYER", "BOBPROTV", "IBOPROTV","IBOSTB","IBOSOL", "DUPLEX", "FLIXNET"
    ],
    "userListModules" => [
        'MASA', 'VIRGINIA', 'IBOAPP', 'ABEPLAYERTV', "BOBPLAYER",
        "MACPLAYER", "KTNPLAYER", "ALLPLAYER", "HUSHPLAY", "FAMILYPLAYER", "KING4KPLAYER", "IBOSSPLAYER", "IBOXXPLAYER", "BOBPROTV", "IBOPROTV","IBOSTB","IBOSOL", "DUPLEX", "FLIXNET"
    ],
    "searchUserModules" => [
        'MASA', 'VIRGINIA', 'IBOAPP', 'ABEPLAYERTV', "BOBPLAYER",
        "MACPLAYER", "KTNPLAYER", "ALLPLAYER", "HUSHPLAY", "FAMILYPLAYER", "KING4KPLAYER", "IBOSSPLAYER", "IBOXXPLAYER", "BOBPROTV", "IBOPROTV","IBOSTB","IBOSOL", "DUPLEX", "FLIXNET"
    ],
];